[project]
name = "ai-driven-product-recommendation-platform"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi==0.115.2",
    "uvicorn==0.32.0",
    "pydantic==2.9.2",
    "python-dotenv==1.0.1",
    "requests==2.32.3",
    "openai==1.52.1",
    "psycopg2-binary==2.9.9",
]

[tool.vercel]
entrypoint = "src.api.main:app"
